distance_threshold_factor: 0.08
distance_threshold: 0.03
lambda: 27000
evaluation_threshold: 0.02
min_overlapping_percentage: 0.15
target_radius_factor: 5
number_subclouds: 15
size_source: 250
size_target: 2000
refinement_icp_source_size: 500
refinement_icp_target_size: 2000
min_plane_portion: 0.1
min_plane_distance: 0.04
min_scaling_factor: 0.8
max_scaling_factor: 1.2
max_depth: 3
icp_eps: 1.0e-05
icp_eps2: 1.0e-03
max_icp_it: 300
max_numerical_error: 1.0e-03
max_percentage: 0.7
damping_coefficient: 3
delay_factor: 0.2
remove_plane: 1
max_icp_evaluations: 20
