distance_threshold: 0.02
min_overlapping_percentage: 0.15
target_radius_factor: 1.3
number_subclouds: 5
size_source: 250
size_target: 500
refinement_icp_source_size: 500
refinement_icp_target_size: 2000
evaluation_threshold: 0.015
min_plane_portion: 0.2
min_plane_distance: 0.01
min_scaling_factor: 0.8
max_scaling_factor: 1.2
max_depth: 2
icp_eps: 1.0e-05
max_icp_it: 300
icp_eps2: 0.1
max_numerical_error: 1.0e-05
max_percentage: 0.7
damping_coefficient: 0.5
delay_factor: 0.6

